version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis_dev
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-volume:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  redis-volume:
